os: linux
dist: focal
language: python

services:
    - docker
    - redis

install: bash bin/travis-build.bash
script: bash bin/travis-run.bash

stages:
  - Flake8
  - Tests

jobs:
  include:
    - stage: Flake8
      python: 3.6
      env: FLAKE8=True
      install:
        - pip install flake8==3.5.0
        - pip install pycodestyle==2.3.0
      script:
        - flake8 --version
        # stop the build if there are Python syntax errors or undefined names
        - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan
        # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
        - flake8 . --count --max-line-length=127 --statistics --exclude ckan --exit-zero

    - stage: Tests
      python: "3.6"
      env: CKANVERSION=master
      services:
          - postgresql
          - redis
          - docker

    - python: "2.7"
      env: CKANVERSION=2.9
      services:
          - postgresql
          - redis
          - docker


    - python: "3.6"
      env: CKANVERSION=2.9
      services:
          - postgresql
          - redis
          - docker

    - python: "2.7"
      env: CKANVERSION=2.8
      addons:
        postgresql: '11'
        apt:
          sources:
            - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main'
          packages:
            - postgresql-11

    - python: "2.7"
      env: CKANVERSION=2.7
      addons:
        postgresql: '9.6'
        apt:
          sources:
            - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main'
          packages:
            - postgresql-9.6

    - python: "2.7"
      env: CKANVERSION=2.6
      addons:
        postgresql: '9.6'
        apt:
          sources:
            - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main'
          packages:
            - postgresql-9.6


cache:
  directories:
    - $HOME/.cache/pip
